<a href="https://colab.research.google.com/github/seohyeon1578/TensorFlow/blob/main/numpyEx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
# rank가 1인 배열

In [2]:
a = np.array([1, 2, 3])
b = [1, 2, 3]

print(a)
print(b)

[1 2 3]
[1, 2, 3]


In [3]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'list'>


In [4]:
# shape
a.shape

(3,)

In [5]:
temp = 3,
print(temp)

(3,)


In [6]:
a.ndim

1

In [ ]:
# rank가 2인 배열

In [7]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b.shape

(2, 3)

In [9]:
b.ndim

2

In [10]:
b.itemsize

8

In [12]:
a.dtype

dtype('int64')

In [13]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
# 3행 4열로
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
# 특수한 행렬
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.full((3, 3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [20]:
# 기술통계
x = np.array([18, 5, 10, 2, 3, -3, -5, -30, 15, 6, 78, -13, 9, 5, 5, 6, 7, 0, 80, -4])
x

array([ 18,   5,  10,   2,   3,  -3,  -5, -30,  15,   6,  78, -13,   9,
         5,   5,   6,   7,   0,  80,  -4])

In [21]:
len(x)

20

In [23]:
# 평균
np.mean(x)

9.7

In [24]:
# 분산
np.var(x)

633.01

In [26]:
# 표준편차
np.std(x)

25.15968998219175

In [27]:
# 최대값, 최소값, 중앙값
print(np.max(x), np.min(x), np.median(x))

80 -30 5.0


In [ ]:
# 배열 인덱싱

In [28]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# [1, 2
#  5, 6]

In [33]:
b = a[:2, :2]
b

array([[1, 2],
       [5, 6]])

In [ ]:
#[2, 3
# 6, 7]

In [35]:
c = a[:2, 1:3]
c

array([[2, 3],
       [6, 7]])

In [36]:
b[0, 0] = 100
b

array([[100,   2],
       [  5,   6]])

In [37]:
a

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [ ]:
# a 원본배열을 잘라간 b 는 부분배열, 부분배열을 수정하면 a 원본배열도 수정됨에 유의  
# (주소가 같기 때문)

In [ ]:
# [5, 6, 7, 8] => 1행 추출

In [41]:
d = a[1, :]
d

array([5, 6, 7, 8])

In [42]:
print(d.ndim, d.shape)

1 (4,)


In [ ]:
# [2, 6, 10] => 2열 추출

In [43]:
e = a[:, 1]
e

array([ 2,  6, 10])

In [44]:
print(e.ndim, e.shape)

1 (3,)


In [45]:
f = a[:, 1:2]
f

array([[ 2],
       [ 6],
       [10]])

In [46]:
print(f.ndim, f.shape)

2 (3, 1)


In [ ]:
# 난수 (Random NUmber)

In [47]:
np.random.rand(5)  # 0부터 1사이의 실수  (5번수행)

array([0.94818976, 0.64611327, 0.61273902, 0.21371322, 0.79561296])

In [53]:
np.random.seed(0)   # 씨앗값
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [55]:
np.random.seed(0) 
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [54]:
np.random.seed(2)
np.random.rand(5)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ])

In [ ]:
# np.random.randn()   # 가우시안 표준 정규 분포 - 실수

In [56]:
np.random.randn(5)

array([-0.84272405,  1.96992445,  1.26611853, -0.50587654,  2.54520078])

In [57]:
# np.random.randint(low, high, size) # 균일 분포 - 정수
np.random.randint(5)

1

In [58]:
np.random.randint(10, 50, 5)

array([23, 18, 19, 30, 26])

In [ ]:
# 로또번호 6개

In [59]:
np.random.randint(1, 46, 6)

array([ 6, 16,  1, 19, 36, 25])

In [ ]:
# 로또번호 5천원

In [65]:
np.random.randint(1, 46, [5, 6])    # 문제: 겹치는 숫자 있음

array([[40, 42, 36, 39, 12, 19],
       [28,  1, 15, 36, 13, 43],
       [21, 12,  5,  7,  5,  4],
       [13, 37, 41, 15, 16, 21],
       [36, 24, 16, 14, 22,  6]])

In [ ]:
# 데이터 샘플링 : 이미 있는 데이터 집합에서 무작위로 선택하는 것
# np.random.choice(원본데이터, size, replace=True/False, p)

In [66]:
np.random.choice(5, 5, replace=False)

array([2, 4, 0, 3, 1])

In [70]:
np.random.choice(5, 3, replace=False)

array([2, 3, 1])

In [74]:
# np.random.choice(5, 10, replace=False)  #오류

In [72]:
np.random.choice(5, 10, replace=True)

array([0, 3, 1, 1, 4, 0, 0, 3, 2, 3])

In [73]:
np.random.choice(5, 10, replace=True, p=[0.1, 0, 0, 0.3, 0.6])

array([3, 4, 4, 4, 4, 3, 4, 4, 4, 3])

In [75]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.random.shuffle(x)
x

array([6, 4, 0, 2, 1, 7, 5, 3, 8, 9])